version: '2'
services:
    db:
        image: postgres:11-alpine
        ports:
        - "15434:5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "techblog"
